title: Tim Barnes
# email: your-email@example.com
description: >-
    How am I not myself?
baseurl: ""
url: "https://timbobbarnes.github.io"
# twitter_username: timbobbarnes
# github_username:  timbobbarnes

# Build settings
theme: minima
